services:
  web:
    image: sawbaw1/devops-midterm:latest
    container_name: midterm_web
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/products_db
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: midterm_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=products_db
    volumes:
      - mongo_data:/data/db
      - ./dump:/dump
    networks:
      - app_network

volumes:
  uploads_data:
    driver: local
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge